tools:
  remember:
    signature: |
      remember <update_type> <memory_area> <title> <text>
    docstring: >
      Store information in long-term memory that will be valuable for future sessions.
      Each memory is automatically embedded and timestamped when stored.

      Usage Guidelines:
      - Core: Store essential facts that affect every interaction
        Examples: User's name, role, major preferences, interaction style
        Max 50 chars, automatically included in all future sessions
      
      - Human: Store contextual information about the user
        Examples: Technical expertise, project goals, past collaborations
        Max 500 chars, available for recall when relevant
      
      - Archival: Store task-specific knowledge and decisions
        Examples: Design rationales, architecture decisions, implementation patterns
        Max 2000 chars, searchable reference for similar future tasks

      Best Practices:
      - Store information that will inform future decision-making
      - Focus on patterns and preferences rather than temporary details
      - Consider what context would help you make better recommendations
      - Update memories when you discover they're outdated
    arguments:
      - name: update_type
        type: string
        description: >
          'new' creates a memory if title doesn't exist in memory_area
          'overwrite' updates an existing memory
          Returns error if existence condition not met
        required: true
      - name: memory_area
        type: string
        description: >
          Where to store the memory:
          'core': Critical memories injected into every session (max 50 chars)
          'human': Information about the human (max 500 chars)
          'archival': Task/domain knowledge (max 2000 chars)
        required: true
      - name: title
        type: string
        description: "Unique identifier within the memory_area (max 100 characters)"
        required: true
      - name: text
        type: string
        description: "Content to remember. Will be embedded for semantic search. Length limit depends on memory_area."
        required: true
